import type {
  AltaEvent,
  ControlState,
  CredentialInventory,
  MvpStatus,
  PaperCapitalStatus,
  RuntimeDetail,
} from "./types";

const now = Date.now();
const time = (minutes: number) =>
  new Date(now - minutes * 60_000).toISOString();

export const previewControl: ControlState = {
  console: {
    protocolVersion: 4,
    instanceId: "synthetic-preview",
    startedAt: time(15),
    uptimeSeconds: 900,
  },
  runtime: {
    installed: true,
    ready: true,
    platformActive: true,
    endpoint: "http://127.0.0.1:8876",
    capitalMode: "disabled",
    host: { state: "running", processId: 48120, processAlive: true },
    supervisor: { state: "running", childPid: 48127, childProcessAlive: true },
  },
  environment: {
    docker: { ready: true, version: "preview" },
    services: {
      configured: true,
      states: { postgres: "healthy", redis: "healthy" },
    },
  },
  operation: null,
  safety: {
    environment: "shadow",
    capitalMode: "disabled",
    brokerEnvironment: "PAPER",
    dashboardBinding: "127.0.0.1",
  },
};

export const previewCredentials: CredentialInventory = {
  revision: "synthetic-preview",
  verification: {
    checkedAt: time(2),
    expiresAt: new Date(now + 13 * 60_000).toISOString(),
    stale: false,
  },
  configuredSlots: [
    "deepseek",
    "xai",
    "kimi",
    "massive",
    "finlight",
    "finnhub",
  ],
  slots: [
    ["deepseek", "DeepSeek", "models", true, "demo-fp-deepseek"],
    ["xai", "xAI / Grok", "models", true, "demo-fp-xai"],
    ["kimi", "Kimi / Moonshot", "models", true, "demo-fp-kimi"],
    ["massive", "Massive", "market_data", true, "demo-fp-massive"],
    ["finlight", "Finlight", "news", true, "demo-fp-finlight"],
    ["finnhub", "Finnhub", "market_data", true, "demo-fp-finnhub"],
    ["brave", "Brave Search", "research", false, null],
    ["jina", "Jina Reader", "research", false, null],
    ["openalex", "OpenAlex", "research", false, null],
  ].map(([slot, label, category, configured]) => ({
    slot: String(slot),
    label: String(label),
    category: category as CredentialInventory["slots"][number]["category"],
    purpose: "Synthetic preview metadata",
    configured: Boolean(configured),
    operational: Boolean(configured) || slot === "jina" || slot === "openalex",
    credentialRequirement: ["brave", "jina", "openalex", "finnhub"].includes(
      String(slot),
    )
      ? ("optional" as const)
      : ("required" as const),
    availableWithoutCredential:
      slot === "jina" || slot === "openalex" ? true : undefined,
    source: configured ? `external credential file (${slot}.key)` : "missing",
    sourceKind: configured ? "external" : "missing",
    editable: true,
    fingerprint: null,
    verification: configured
      ? {
          status:
            slot === "finlight"
              ? ("auth_rejected" as const)
              : slot === "finnhub"
                ? ("rate_limited" as const)
                : ("healthy" as const),
          reason:
            slot === "finlight"
              ? "authentication_rejected"
              : slot === "finnhub"
                ? "provider_rate_limited"
                : null,
          checkedAt: time(2),
          latencyMs: slot === "massive" ? 184 : 96,
          httpStatus:
            slot === "finlight" ? 401 : slot === "finnhub" ? 429 : 200,
        }
      : slot === "jina" || slot === "openalex"
        ? {
            status: "not_required" as const,
            reason: null,
            checkedAt: time(2),
            latencyMs: null,
            httpStatus: null,
          }
        : {
            status: "not_configured" as const,
            reason: "credential_missing",
            checkedAt: null,
            latencyMs: null,
            httpStatus: null,
          },
  })),
  providerNetwork: [
    {
      category: "market_and_regulatory",
      providers: ["Nasdaq", "SEC EDGAR", "FRED", "BLS", "World Bank"],
    },
    {
      category: "news_and_discovery",
      providers: ["GDELT", "Google News RSS", "GlobeNewswire"],
    },
    {
      category: "research_and_social",
      providers: ["Crossref", "arXiv", "Reddit", "Bluesky"],
    },
  ],
  trading: {
    provider: "Tiger Trade",
    mode: "paper_only",
    configured: true,
    editable: false,
    source: "external credential file (tiger-paper.properties)",
    sourceKind: "external",
    fingerprint: null,
    status: "configured_external_capital_disabled",
    authorizationEnabled: false,
    authorizationPosture: "paper_ready_disabled",
  },
};

export const previewCapital: PaperCapitalStatus = {
  version: 1,
  provider: "Tiger Trade",
  environment: "PAPER",
  configured: true,
  requestedEnabled: false,
  enabled: false,
  authorizationGeneration: 1,
  closeOnly: false,
  drainRequired: false,
  posture: "paper_ready_disabled",
  accountFingerprint: "8f5c2a17d309",
  configurationFingerprint: "c1287a4359de",
  mutationPolicy: "risk_budgeted_limit_day_v1",
  riskPolicy: {
    maxOrderNotional: "10000",
    maxOpenPositions: "4",
    maxDispatchQuoteAgeSeconds: "10",
  },
  instrumentPolicy: "us_stock_only",
  outsideRegularHours: false,
  requiresStoppedRuntime: true,
  lastChangedAt: time(48),
  lastPreflightAt: time(6),
  configurationError: null,
  authorizationError: null,
  snapshotError: null,
  snapshot: {
    paper: true,
    accountBinding: true,
    accountFingerprint: "8f5c2a17d309",
    observedAt: time(6),
    brokerUpdatedAt: time(7),
    savedAt: time(6),
    positionCount: 2,
    openOrderCount: 0,
    recentOrderCount: 3,
    mutationPolicy: "risk_budgeted_limit_day_v1",
    maxOrderNotional: "10000",
    assets: {
      currency: "USD",
      cashBalance: "98234.18",
      cashAvailableForTrade: "97640.00",
      netLiquidation: "100418.20",
      grossPositionValue: "2184.02",
      buyingPower: "195280.00",
      unrealizedPnl: "42.16",
      realizedPnl: "18.40",
      maintenanceMargin: "655.21",
    },
    positions: [
      {
        symbol: "SPY",
        securityType: "STK",
        currency: "USD",
        quantity: "12",
        averageCost: "642.10",
        marketPrice: "643.28",
        marketValue: "643.28",
        unrealizedPnl: "1.18",
        unrealizedPnlPercent: "0.0018",
        realizedPnl: "0",
        todayPnl: "1.18",
        salableQuantity: "12",
      },
      {
        symbol: "QQQ",
        securityType: "STK",
        currency: "USD",
        quantity: "8",
        averageCost: "585.40",
        marketPrice: "584.92",
        marketValue: "584.92",
        unrealizedPnl: "-0.48",
        unrealizedPnlPercent: "-0.0008",
        realizedPnl: "0",
        todayPnl: "-0.48",
        salableQuantity: "8",
      },
    ],
    orders: [
      {
        reference: "a74f18d2c61b903e",
        symbol: "SPY",
        securityType: "STK",
        side: "BUY",
        orderType: "LMT",
        status: "FILLED",
        quantity: "1",
        filled: "1",
        remaining: "0",
        limitPrice: "642.10",
        averageFillPrice: "642.10",
        commission: "0.01",
        realizedPnl: "0",
        timeInForce: "DAY",
        outsideRegularHours: false,
        createdAt: time(52),
        updatedAt: time(51),
        filledAt: time(51),
      },
    ],
  },
  audit: [
    {
      id: "capital-audit-preview",
      action: "preflight_refreshed",
      result: "succeeded",
      knownAt: time(6),
      accountFingerprint: "8f5c2a17d309",
    },
  ],
};

export const previewRuntime: RuntimeDetail = {
  minds: [
    {
      id: "structural-flow",
      knownAt: time(1),
      turnCount: 14,
      contextTokens: 18340,
      modelProvider: "deepseek",
      modelId: "reasoner",
      rollingSummary:
        "Cross-venue flow dislocation; checking persistence and borrow constraints.",
    },
    {
      id: "volatility-surface",
      knownAt: time(2),
      turnCount: 9,
      contextTokens: 12780,
      modelProvider: "xai",
      modelId: "grok",
      rollingSummary:
        "Term structure moved ahead of realized dispersion; seeking a falsifiable carrier.",
    },
    {
      id: "fundamental-change",
      knownAt: time(4),
      turnCount: 11,
      contextTokens: 15420,
      modelProvider: "kimi",
      modelId: "thinking",
      rollingSummary:
        "Revision breadth diverged from headline consensus; validating source independence.",
    },
  ],
  sourceCursors: [
    { source: "massive", cursor: "2026-08-29T07:19:00Z", knownAt: time(1) },
    { source: "sec", cursor: "feed:28419", knownAt: time(3) },
  ],
  researchAttention: {
    version: "alta-research-attention-v2",
    knownAt: time(1),
    observedThrough: time(46),
    maximumWindow: 64,
    minimumSample: 4,
    concentrationThreshold: "0.50",
    sampleSize: 6,
    uniqueEntities: 2,
    topEntity: "NVDA",
    topEntityShare: "0.8333",
    concentrationHhi: "0.7222",
    effectiveBreadth: "1.38",
    uniqueArchetypes: 3,
    archetypeEffectiveBreadth: "2.57",
    horizonMix: { short: 2, medium: 3, long: 1 },
    directionMix: { positive: 3, negative: 2, neutral: 1, unknown: 0 },
    posture: "concentrated",
    continuationScoutId: "change_event_scout",
    assignments: [
      {
        scoutId: "change_event_scout",
        mode: "continue_lead",
        deprioritizedEntities: [],
        targetArchetype: "operating artifact inflection",
        targetHorizonBucket: "medium",
        directive: "Retain the single NVDA continuation seat.",
      },
      ...[
        "market_dislocation_scout",
        "causal_policy_scout",
        "expectation_gap_scout",
      ].map((scoutId) => ({
        scoutId,
        mode: "expand_coverage" as const,
        deprioritizedEntities: ["NVDA"],
        targetArchetype: "policy second-order beneficiary",
        targetHorizonBucket: "long" as const,
        directive: "Expand independent entity coverage beyond NVDA.",
      })),
    ],
    warning:
      "Research attention is concentrated; one continuation seat is preserved while the remaining Trader Minds expand entity coverage.",
  },
  opportunityContinuity: {
    version: "alta-opportunity-continuity-v2",
    knownAt: time(1),
    scanLimit: 32,
    frozenLimit: 4,
    registryActive: 7,
    scannedActive: 7,
    frozenActive: 4,
    pendingQuestions: 3,
    deferredQuestions: 6,
    nextResearchDueAt: time(-360),
    expiringActive: 2,
    staleActive: 0,
    oldestActiveDays: 41,
    earliestDecisionDeadlineAt: time(-96),
    selectedOpportunityIds: [
      "opportunity-pricing",
      "opportunity-policy",
      "opportunity-flow",
      "opportunity-quality",
    ],
    priorityOpportunityIds: ["opportunity-pricing", "opportunity-policy"],
    selectionTruncated: true,
    registryScanSaturated: false,
    posture: "expiring",
    warning:
      "Two active Opportunities are inside their next fourteen-day decision window.",
  },
  researchOperations: {
    version: "alta-research-operations-v4",
    posture: "cross_checked",
    windowRuns: 16,
    candidateRuns: 5,
    noOpRuns: 11,
    failedRuns: 0,
    completedToolCalls: 57,
    failedToolCalls: 1,
    uniqueSourceDomains: 23,
    independentEvidenceOrigins: 39,
    citedSources: 51,
    sourceRoleCollisions: 2,
    sourceFamilies: ["discovery", "market_data", "primary_web", "social"],
    crossCheckedRuns: 4,
    screenGradeRuns: 3,
    retriedRuns: 3,
    retryRecoveredRuns: 2,
    contractRejectedRuns: 1,
    deadlineFailedRuns: 0,
    followUpAssignedRuns: 4,
    followUpExecutedRuns: 4,
    followUpNoOpRuns: 3,
    totalTokens: 42680,
    averageLatencyMs: 18420,
    minds: [
      ["change_event_scout", "cross_checked", 17, 4],
      ["market_dislocation_scout", "active", 12, 4],
      ["causal_policy_scout", "screen_grade", 15, 3],
      ["expectation_gap_scout", "cross_checked", 14, 4],
    ].map(([scoutId, posture, calls, domains], index) => ({
      scoutId: String(scoutId),
      posture: posture as "active" | "cross_checked" | "screen_grade",
      lastRunAt: time(4 + index * 3),
      latestStatus: "succeeded",
      latestErrorCode: null,
      windowRuns: 4,
      candidateRuns: index < 2 ? 2 : index === 2 ? 0 : 1,
      noOpRuns: index < 2 ? 2 : index === 2 ? 4 : 3,
      failedRuns: 0,
      completedToolCalls: Number(calls),
      failedToolCalls: index === 2 ? 1 : 0,
      uniqueSourceDomains: Number(domains),
      independentEvidenceOrigins: Number(domains) + 5,
      citedSources: 12 + index,
      sourceRoleCollisions: index === 2 ? 2 : 0,
      sourceFamilies: ["discovery", "market_data", "primary_web"],
      evidenceRoles:
        index === 1
          ? ["primary_fact", "mechanism", "market_context"]
          : ["primary_fact", "mechanism", "market_context", "counterevidence"],
      crossCheckedRuns: index === 0 || index === 3 ? 2 : 0,
      screenGradeRuns: index === 2 ? 3 : 0,
      retriedRuns: index < 3 ? 1 : 0,
      retryRecoveredRuns: index < 2 ? 1 : 0,
      contractRejectedRuns: index === 2 ? 1 : 0,
      deadlineFailedRuns: 0,
      followUpAssignedRuns: index < 2 ? 2 : 0,
      followUpExecutedRuns: index < 2 ? 2 : 0,
      followUpNoOpRuns: index === 0 ? 1 : index === 1 ? 2 : 0,
      latestAttemptCount: index < 3 ? 2 : 1,
      totalTokens: 9800 + index * 580,
      averageLatencyMs: 16200 + index * 940,
    })),
    disclosure:
      "Saved tool provenance and diligence outcomes only; queries, arguments, credentials, source text, and private reasoning are not exposed.",
  },
  alpha: {
    measurement: "realized_shadow_cost_adjusted",
    closedPositions: 12,
    openPositions: 2,
    meanRealizedAlphaBps: "18.40",
    cumulativeNetPnl: "418.20",
    lastMeasuredAt: time(28),
    alphaEvidence: {
      posture: "insufficient_sample",
      sampleSize: 12,
      minimumSample: 30,
      meanAlphaBps: "18.40",
      confidence95LowerBps: "-41.20",
      confidence95UpperBps: "78.00",
      researchTrials: 86,
      selectionPolicyVersion: "alta-research-selection-v1",
      selectionCriticalZ: "3.44",
      selectionAdjustedConfidence95LowerBps: "-86.10",
      selectionAdjustedLowerBoundAboveZero: false,
    },
    capitalGovernance: {
      posture: "collecting",
      capitalMultiplier: "0.50",
      sampleSize: 12,
      windowSize: 12,
      recentMeanAlphaBps: "18.40",
      confidence95LowerAlphaBps: "-41.20",
      confidence95UpperAlphaBps: "78.00",
      researchTrials: 86,
      selectionAdjustedLowerAlphaBps: "-86.10",
      selectionCriticalZ: "3.44",
      maxDrawdownNavBps: "21.50",
      evidencePosture: "insufficient_sample",
    },
    underwritingCalibration: {
      posture: "exploratory_only",
      sampleSize: 12,
      minimumSample: 30,
      meanForecastErrorBps: "-74.60",
      meanAbsoluteErrorBps: "118.20",
      directionalHitRate: "0.58",
    },
    forecastCalibrationGovernance: {
      posture: "collecting",
      expressionKind: "stock",
      capitalMultiplier: "1",
      sampleSize: 12,
      windowSize: 12,
      minimumSample: 30,
      meanForecastErrorBps: "-74.60",
      meanAbsoluteErrorBps: "118.20",
      directionalHitRate: "0.58",
      alphaReserveBps: "0",
    },
    pathDiagnostics: {
      posture: "collecting",
      measuredPositions: 12,
      minimumSample: 30,
      meanMaximumFavorableExcursionBps: "164.30",
      meanMaximumAdverseExcursionBps: "-91.70",
      meanMaximumDrawdownBps: "182.40",
      meanExitCaptureRatio: "0.42",
      positiveExcursionMissRate: "0.17",
      warning:
        "Observed excursions are sparse decision diagnostics, not intraday backtest data or an automatic exit rule.",
    },
    executionQuality: {
      posture: "collecting",
      measuredPositions: 12,
      minimumSample: 30,
      meanEstimatedCostBps: "18.40",
      meanRealizedCostBps: "23.90",
      meanCostSurpriseBps: "5.50",
      withinBudgetRate: "0.58",
      openFillRate: "0.80",
      openFills: 12,
      openNoFills: 3,
      exitFills: 12,
      exitNoFills: 1,
      warning:
        "Execution TCA is based on forward Shadow quotes and modeled fills; it is not live-market capacity or broker performance.",
    },
    executionCostGovernance: {
      stock: {
        policyVersion: "alta-execution-cost-governance-v1",
        sourcePortfolioPolicyVersion: "alta-portfolio-risk-v8",
        expressionKind: "stock",
        posture: "collecting",
        sampleSize: 12,
        windowSize: 12,
        minimumSample: 30,
        meanEstimatedCostBps: "18.40",
        meanRealizedCostBps: "23.90",
        meanCostSurpriseBps: "5.50",
        meanAbsoluteSurpriseBps: "8.20",
        withinBudgetRate: "0.58",
        alphaReserveBps: "0",
      },
      etf: {
        policyVersion: "alta-execution-cost-governance-v1",
        sourcePortfolioPolicyVersion: "alta-portfolio-risk-v8",
        expressionKind: "etf",
        posture: "collecting",
        sampleSize: 0,
        windowSize: 0,
        minimumSample: 30,
        alphaReserveBps: "0",
      },
      option: {
        policyVersion: "alta-execution-cost-governance-v1",
        sourcePortfolioPolicyVersion: "alta-portfolio-risk-v8",
        expressionKind: "option",
        posture: "collecting",
        sampleSize: 0,
        windowSize: 0,
        minimumSample: 30,
        alphaReserveBps: "0",
      },
    },
    portfolioRisk: {
      policyVersion: "alta-portfolio-risk-v8",
      posture: "within_limits",
      knownOpenPositions: 2,
      referenceNav: "1000000",
      grossNotional: "17800",
      grossNavBps: "178",
      grossLimitNavBps: "800",
      aggregateStressLoss: "4450",
      stressNavBps: "44.5",
      stressLimitNavBps: "100",
      underlyingLimitNavBps: "150",
      alphaSourceLimitNavBps: "300",
      catalystLimitNavBps: "200",
      systematicExposureLimitNavBps: "200",
      mostConstrainedBucket: {
        kind: "systematic_exposure",
        key: "growth_duration",
        grossNavBps: "144",
        limitNavBps: "200",
        utilization: "0.72",
      },
      underlyingBuckets: [
        {
          underlyingKey: "MSFT",
          openPositions: 1,
          grossNotional: "9800",
          grossNavBps: "98",
          estimatedStressLoss: "2450",
        },
        {
          underlyingKey: "SPY",
          openPositions: 1,
          grossNotional: "8000",
          grossNavBps: "80",
          estimatedStressLoss: "2000",
        },
      ],
      alphaSourceBuckets: [
        {
          alphaSource: "earnings_revision",
          openPositions: 1,
          grossNotional: "9800",
          grossNavBps: "98",
          estimatedStressLoss: "2450",
        },
        {
          alphaSource: "relative_value",
          openPositions: 1,
          grossNotional: "8000",
          grossNavBps: "80",
          estimatedStressLoss: "2000",
        },
      ],
      catalystBuckets: [
        {
          catalystKey: "msft-q1-cloud-mix",
          openPositions: 1,
          grossNotional: "9800",
          grossNavBps: "98",
          estimatedStressLoss: "2450",
        },
      ],
      systematicExposureBuckets: [
        {
          tag: "growth_duration",
          grossNotional: "14400",
          grossNavBps: "144",
        },
        {
          tag: "market_beta",
          grossNotional: "12800",
          grossNavBps: "128",
        },
      ],
    },
    warning:
      "Alpha is unproven: the forward Shadow sample is below the minimum.",
  },
  config: {
    autonomousStatus: "waiting",
    currentCycleId: "cycle-20260829-0717",
    lastHeartbeatAt: time(0),
    lastCycleResult: "completed",
    nextCycleAt: new Date(now + 8 * 60_000).toISOString(),
    consecutiveFailures: 0,
    capitalMode: "disabled",
  },
};

export const previewStatus: MvpStatus = {
  status: "MVP_RUNNING",
  environment: "shadow",
  currentPipelineId: "cycle-20260829-0717",
  eventCursor: 1842,
  sources: [
    { id: "massive", knownAt: time(1), posture: "healthy", freshness: "live" },
    { id: "sec", knownAt: time(3), posture: "healthy", freshness: "current" },
    {
      id: "web-research",
      knownAt: time(4),
      posture: "bounded",
      freshness: "current",
    },
  ],
  pipeline: [
    {
      id: "cycle-20260829-0717",
      knownAt: time(1),
      eventType: "mvp.pipeline.completed",
      detail: { status: "MVP_RUNNING" },
    },
  ],
  runs: [],
  agents: [
    {
      id: "structural-flow",
      runId: "run-sf-184",
      status: "completed",
      knownAt: time(1),
      modelProvider: "deepseek",
      modelId: "reasoner",
      latencyMs: 18320,
      usage: { input_tokens: 8200, output_tokens: 1880 },
    },
    {
      id: "disconfirming",
      runId: "run-dc-092",
      status: "completed",
      knownAt: time(2),
      modelProvider: "xai",
      modelId: "grok",
      latencyMs: 22110,
      usage: { input_tokens: 6900, output_tokens: 1420 },
    },
    {
      id: "committee-moderator",
      runId: "run-cm-067",
      status: "running",
      knownAt: time(0),
      modelProvider: "openai",
      modelId: "gpt-5.6",
      latencyMs: 8240,
      usage: { input_tokens: 4100 },
    },
    {
      id: "expression",
      runId: "run-ex-054",
      status: "waiting",
      knownAt: time(0),
      modelProvider: "kimi",
      modelId: "thinking",
    },
    {
      id: "audit",
      runId: "run-au-051",
      status: "waiting",
      knownAt: time(0),
      modelProvider: "openai",
      modelId: "gpt-5.6",
    },
  ],
  candidates: [
    {
      id: "cand-294",
      freshnessState: "live",
      freshnessAt: time(11),
      title: "Index rebalance flow asymmetry",
      knownAt: time(11),
      alphaArchetype: "structural-flow",
    },
    {
      id: "cand-293",
      freshnessState: "live",
      freshnessAt: time(19),
      title: "Post-event volatility repricing",
      knownAt: time(19),
      alphaArchetype: "volatility",
    },
  ],
  opportunities: [
    {
      id: "opp-118",
      actionableNow: true,
      freshnessState: "live",
      freshnessAt: time(4),
      title: "Delayed basket pressure after constituent migration",
      status: "under_review",
      knownAt: time(4),
      foundryState: "complete",
    },
    {
      id: "opp-117",
      actionableNow: true,
      freshnessState: "current",
      freshnessAt: time(31),
      title: "Revision breadth versus crowded consensus",
      status: "ranked",
      knownAt: time(31),
      foundryState: "complete",
    },
    {
      id: "opp-116",
      actionableNow: true,
      freshnessState: "current",
      freshnessAt: time(48),
      title: "Short-dated skew normalization",
      status: "expressed",
      knownAt: time(48),
      foundryState: "complete",
    },
  ],
  ranks: [
    {
      id: "rank-118",
      opportunityId: "opp-118",
      book: "opportunity_1_90d",
      rankingRunId: "preview-ranking-latest",
      rankingRunItemCount: 2,
      rankingRunComplete: true,
      position: 1,
      score: "0.81",
      knownAt: time(2),
    },
    {
      id: "rank-117",
      opportunityId: "opp-117",
      book: "opportunity_1_90d",
      rankingRunId: "preview-ranking-latest",
      rankingRunItemCount: 2,
      rankingRunComplete: true,
      position: 2,
      score: "0.73",
      knownAt: time(28),
    },
  ],
  expressions: [
    {
      id: "expr-118",
      opportunityId: "opp-118",
      kind: "market-neutral-basket",
      status: "validated",
      knownAt: time(1),
    },
    {
      id: "expr-116",
      opportunityId: "opp-116",
      kind: "defined-risk-options",
      status: "validated",
      knownAt: time(42),
    },
  ],
  shadowPositions: [
    {
      id: "pos-041",
      expressionId: "expr-118",
      symbol: "BASKET",
      status: "observing",
      quantity: 1,
      knownAt: time(1),
      openedAt: time(1),
    },
  ],
  assessments: [
    {
      id: "assessment-118-a",
      opportunityId: "opp-118",
      assessor: "thesis",
      verdict: "advance",
      score: "0.84",
      recommendation: "Advance with tighter liquidity evidence",
      confidence: "0.72",
      knownAt: time(3),
    },
    {
      id: "assessment-118-b",
      opportunityId: "opp-118",
      assessor: "disconfirming",
      verdict: "conditional",
      score: "0.61",
      recommendation: "Reject if impact dissipates inside two sessions",
      confidence: "0.68",
      knownAt: time(2),
    },
  ],
  discussions: [
    {
      id: "discussion-118-1",
      opportunityId: "opp-118",
      eventType: "committee.argument.recorded",
      knownAt: time(2),
      detail: {
        speaker: "thesis",
        summary: "Persistent mechanical flow has a measurable decay profile.",
      },
    },
    {
      id: "discussion-118-2",
      opportunityId: "opp-118",
      eventType: "committee.challenge.recorded",
      knownAt: time(1),
      detail: {
        speaker: "disconfirming",
        summary: "Observed pressure may be ordinary closing-auction imbalance.",
      },
    },
  ],
};

export const previewEvents: AltaEvent[] = [
  {
    cursor: 1842,
    eventId: "evt-1842",
    eventType: "committee.deliberation.started",
    aggregateType: "opportunity",
    aggregateId: "opp-118",
    environment: "shadow",
    knownAt: time(0),
    payload: {
      participants: ["thesis", "disconfirming", "moderator"],
      stage: "evidence_conflict",
    },
  },
  {
    cursor: 1841,
    eventId: "evt-1841",
    eventType: "assessment.locked",
    aggregateType: "opportunity",
    aggregateId: "opp-118",
    environment: "shadow",
    knownAt: time(2),
    payload: { assessor: "disconfirming", verdict: "conditional" },
  },
  {
    cursor: 1840,
    eventId: "evt-1840",
    eventType: "run.completed",
    aggregateType: "run",
    aggregateId: "run-dc-092",
    environment: "shadow",
    knownAt: time(2),
    payload: {
      role: "disconfirming",
      artifactKinds: ["assessment", "evidence_map"],
    },
  },
  {
    cursor: 1839,
    eventId: "evt-1839",
    eventType: "opportunity.completed",
    aggregateType: "opportunity",
    aggregateId: "opp-118",
    environment: "shadow",
    knownAt: time(4),
    payload: { completeness: "complete", memberCandidates: 3 },
  },
  {
    cursor: 1838,
    eventId: "evt-1838",
    eventType: "candidate.discovered",
    aggregateType: "candidate",
    aggregateId: "cand-294",
    environment: "shadow",
    knownAt: time(11),
    payload: { scout: "structural-flow", archetype: "flow_dislocation" },
  },
];
